---
- name: Sign our CSR with acme-tiny
  shell: >
    python3 {{ acme_ssl_base_folder }}/acme-tiny/acme_tiny.py
    --account-key "{{ acme_ssl_base_folder }}/account.key"
    --csr "{{ acme_ssl_base_folder }}/{{ item }}/domain.csr"
    --acme-dir "{{ acme_challenges_folder_path }}"
    > {{ acme_ssl_base_folder }}/{{ item }}/signed.crt
- name: Fetch Lets Encrypt intermediate cert
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
    dest: "{{ acme_ssl_base_folder }}/{{ item }}/intermediate.pem"
    force: yes
- name: Create fullchain cert
  shell: "cat signed.crt intermediate.pem > chained.pem"
  args:
    chdir: "{{ acme_ssl_base_folder }}/{{ item }}"
  notify: nginx restart
- name: setup domain fullchain perms
  file:
    path: "{{ acme_ssl_base_folder }}/{{ item }}/chained.pem"
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0640
  become: no

