---
- name: "Setup SSL domains folders for {{ item }}"
  file:
    path: "{{ ssl_base_folder }}/{{ item }}"
    state: directory
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0750
- name: Ensure that a domain private key exists
  shell: "openssl genrsa 4096 > {{ ssl_base_folder }}/{{ item }}/domain.key"
  args:
    creates: "{{ ssl_base_folder }}/{{ item }}/domain.key"
  become: yes
  become_user: "{{ acme_user }}"
- name: setup domain private key perms
  file:
    path: "{{ ssl_base_folder }}/{{ item }}/domain.key"
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0640
- name: Do we have a certificate?
  stat: "path={{ ssl_base_folder }}/{{ item }}/chained.pem"
  register: cert_stat
- name: Is certificate too old?
  find:
    paths: "{{ ssl_base_folder }}/{{ item }}"
    pattern: "chained.pem"
    age: 30d
  register: cert_age_find
- include: sign.yml
  become: yes
  become_user: "{{ acme_user }}"
  when: cert_age_find.matched > 0 or not cert_stat.stat.exists

