---
- name: Setup SSL domains folders
  file:
    path: "{{ ssl_base_folder }}/{{ item }}"
    state: directory
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0750
  with_items: "{{ acme_domains }}"
- name: Ensure that a domain private key exists
  shell: "openssl genrsa 4096 > {{ ssl_base_folder }}/{{ item }}/domain.key"
  args:
    creates: "{{ ssl_base_folder }}/{{ item }}/domain.key"
  become: yes
  become_user: "{{ acme_user }}"
  with_items: "{{ acme_domains }}"
- name: setup domain private key perms
  file:
    path: "{{ ssl_base_folder }}/{{ item }}/domain.key"
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0640
  with_items: "{{ acme_domains }}"
- name: Ensure that we have a domain CSR
  shell: "openssl req -new -sha256 -key {{ ssl_base_folder }}/{{ item }}/domain.key -subj \"/CN={{ item }}\" > {{ ssl_base_folder }}/{{ item }}/domain.csr"
  args:
    creates: "{{ ssl_base_folder }}/{{ item }}/domain.csr"
  become: yes
  become_user: "{{ acme_user }}"
  with_items: "{{ acme_domains }}"
- name: Sign our CSR if needed
  shell: >
    python3 {{ ssl_base_folder }}/acme-tiny/acme_tiny.py
    --account-key "{{ ssl_base_folder }}/account.key"
    --csr "{{ ssl_base_folder }}/{{ item }}/domain.csr"
    --acme-dir "{{ acme_challenges_folder_path }}"
    > {{ ssl_base_folder }}/{{ item }}/signed.crt
  args:
    creates: "{{ ssl_base_folder }}/{{ item }}/signed.crt"
  become: yes
  become_user: "{{ acme_user }}"
  with_items: "{{ acme_domains }}"
- name: Fetch Lets Encrypt intermediate cert
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem
    dest: "{{ ssl_base_folder }}/{{ item }}/intermediate.pem"
  become: yes
  become_user: "{{ acme_user }}"
  with_items: "{{ acme_domains }}"
- name: Create fullchain cert
  shell: "cat signed.crt intermediate.pem > chained.pem"
  args:
    chdir: "{{ ssl_base_folder }}/{{ item }}"
    creates: "{{ ssl_base_folder }}/{{ item }}/chained.pem"
  become: yes
  become_user: "{{ acme_user }}"
  with_items: "{{ acme_domains }}"
- name: setup domain fullchain perms
  file:
    path: "{{ ssl_base_folder }}/{{ item }}/chained.pem"
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0640
  with_items: "{{ acme_domains }}"

